# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)

docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-worker-gcp-community-googlecompute-2020-05-21t21-31-41z
  aws:
    amis:
      us-east-1: ami-0eacf0eb3d45c869a
      us-west-1: ami-01cd13983c49b2958
      us-west-2: ami-046177c829909c334

generic-worker-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0e25602446699a013
      us-west-1: ami-0360493dcdb36682e
      us-west-2: ami-0f8c71fac9219169c
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/2509a1f8589b0b536186f5fe8f043385bf67197f/worker_types/win2012r2/bootstrap.ps1

generic-worker-win2012r2-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0f3df2bd13de80a39
      us-west-1: ami-0060b73fb4d9c6256
      us-west-2: ami-0f4944078691b0096
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-win2012r2-staging-hasr18iepqtggvlswlku
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/mozilla/community-tc-config/ab5c8405d85c10ab7bc59c95d01463396fa3c623/imagesets/generic-worker-win2012r2-staging/bootstrap.ps1

generic-worker-ubuntu-18-04:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0b9e052beaf5738c5
      us-west-1: ami-0e3ee2d095f50facd
      us-west-2: ami-09b6663bf10cb7237
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/ba5c21e60957f5ed3395f848f975a7ae8b147252/worker_types/gwci-linux/bootstrap.sh

generic-worker-ubuntu-18-04-podman:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-00e3c8fc6fd4b185a
      us-west-1: ami-07e52123a8cbe7fd5
      us-west-2: ami-079a6da57f57b2cbe
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/MozillaSecurity

generic-worker-ubuntu-18-04-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-002495dba2e7cf687
      us-west-1: ami-007b53ac7c08420bd
      us-west-2: ami-025672f8a7fd91c1b
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/ba5c21e60957f5ed3395f848f975a7ae8b147252/worker_types/gwci-linux-beta/bootstrap.sh

deepspeech-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-034d956b2bc6814ca
      us-west-1: ami-0daeb6855843297af
      us-west-2: ami-0cb880d23e4cee86e
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/2509a1f8589b0b536186f5fe8f043385bf67197f/worker_types/deepspeech-win/bootstrap.ps1

deepspeech-win2012r2-b:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0872341d0c628f6cc
      us-west-1: ami-09ffad815d651720d
      us-west-2: ami-098978bbb14097810
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/2509a1f8589b0b536186f5fe8f043385bf67197f/worker_types/deepspeech-win/bootstrap.ps1

deepspeech-win2012r2-gpu:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0b45eef050836e1af
      us-west-2: ami-0ad20a403c0cc04a4
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/5d7c08a762b49d173007f12a7bfda6575f00576e/imagesets/deepspeech-win2012r2-gpu/bootstrap.ps1

deepspeech-win2012r2-gpu-b:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0ded0a4e7ec799a7d
      us-west-2: ami-047cf51b693ad7c3a
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://github.com/mozilla/community-tc-config/blob/5d7c08a762b49d173007f12a7bfda6575f00576e/imagesets/deepspeech-win2012r2-gpu/bootstrap.ps1
